add_newline = false

[kubernetes]
symbol = "☸  "
style = "dimmed blue"
disabled = false

[aws]
disabled = true

[terraform]
show_version = true

[rust]
symbol = " "

[character]
symbol = "󿘽 "
vicmd_symbol = "󿘼 "
